// Code generated by ndpgen. DO NOT EDIT.
//
// This file contains export wrappers for the AuthProvider capability.
// It is intended for use in Navidrome plugins built with TinyGo.
//
//go:build wasip1

package authprovider

import (
	"github.com/navidrome/navidrome/plugins/pdk/go/pdk"
)

// AuthStatus describes the provider's current state for the login page and host.
type AuthStatus struct {
	// Enabled indicates the provider is fully configured and can handle logins.
	Enabled bool `json:"enabled"`
	// ButtonText is the label for the SSO button on the login page.
	ButtonText string `json:"buttonText,omitempty"`
	// AutoRedirect indicates the login page should skip the local form and
	// redirect straight to the provider.
	AutoRedirect bool `json:"autoRedirect,omitempty"`
	// ProviderID is a stable identifier of the provider (e.g. "oidc").
	ProviderID string `json:"providerId,omitempty"`
	// Issuer is the identity provider identifier, when applicable.
	Issuer string `json:"issuer,omitempty"`
	// ClientID is the public OAuth2 client identifier, when applicable.
	ClientID string `json:"clientId,omitempty"`
	// Scopes are the OAuth2 scopes requested from the provider, when applicable.
	Scopes []string `json:"scopes,omitempty"`
	// LogoutURL is the provider logout URL used by the admin settings page.
	LogoutURL string `json:"logoutUrl,omitempty"`
	// MatchBy describes how usernames are derived, when applicable.
	MatchBy string `json:"matchBy,omitempty"`
}

// AuthIdentity represents an authenticated user resolved from the provider.
type AuthIdentity struct {
	// Provider is the identity provider name (e.g. "oidc").
	Provider string `json:"provider"`
	// Subject is the provider's immutable subject identifier for the user.
	Subject string `json:"subject"`
	// Username is the username to provision/authenticate in Navidrome.
	Username string `json:"username"`
	// Email is the user's email address, if available.
	Email string `json:"email,omitempty"`
	// DisplayName is the user's display name, if available.
	DisplayName string `json:"displayName,omitempty"`
	// Groups are the user's group memberships, if available.
	Groups []string `json:"groups,omitempty"`
	// IsAdmin indicates the user should be granted admin rights. When true,
	// the host promotes the user to admin on login.
	IsAdmin bool `json:"isAdmin,omitempty"`
	// IDToken is the raw ID token (or equivalent) returned by the provider.
	// Used as an id_token_hint during single sign-out.
	IDToken string `json:"idToken,omitempty"`
	// Claims contains the raw identity claims for display or debugging.
	Claims map[string]any `json:"claims,omitempty"`
}

// ExchangeCodeRequest carries the callback parameters for the code exchange.
type ExchangeCodeRequest struct {
	// Code is the authorization code received on the callback.
	Code string `json:"code"`
	// State is the state echoed back by the provider on the callback.
	State string `json:"state"`
	// Nonce is the nonce value the host stored in the login cookie.
	Nonce string `json:"nonce"`
	// RedirectURI is the same redirect URI that was used to build the
	// authorization URL.
	RedirectURI string `json:"redirectUri"`
}

// GetLoginURLRequest carries the values required to build an authorization URL.
type GetLoginURLRequest struct {
	// State is the CSRF state token generated by the host. Must be included
	// verbatim in the authorization URL.
	State string `json:"state"`
	// Nonce is the request nonce generated by the host. Must be included
	// verbatim in the authorization URL.
	Nonce string `json:"nonce"`
	// RedirectURI is the callback URI the provider must redirect to after
	// user consent.
	RedirectURI string `json:"redirectUri"`
}

// GetLoginURLResponse is the result of GetLoginURL.
type GetLoginURLResponse struct {
	// AuthorizationURL is the full URL the browser should be redirected to.
	AuthorizationURL string `json:"authorizationUrl"`
}

// GetLogoutURLRequest carries the parameters for building a single sign-out URL.
type GetLogoutURLRequest struct {
	// PostLogoutRedirectURI is where the provider should send the browser
	// after the local session has been torn down.
	PostLogoutRedirectURI string `json:"postLogoutRedirectUri,omitempty"`
	// IDTokenHint is the user's ID token, used as the id_token_hint parameter.
	IDTokenHint string `json:"idTokenHint,omitempty"`
}

// GetLogoutURLResponse is the result of GetLogoutURL.
type GetLogoutURLResponse struct {
	// LogoutURL is the provider's single sign-out URL. Empty when the
	// provider does not support it.
	LogoutURL string `json:"logoutUrl,omitempty"`
}

// GetStatusRequest wraps the context the host can provide for a status query.
type GetStatusRequest struct {
	// AppURL is the base URL of the Navidrome web app (e.g. https://nd.local/app).
	// Used by the plugin to build absolute redirect/logout URLs.
	AppURL string `json:"appUrl"`
}

// VerifyBearerRequest carries a bearer token to validate.
type VerifyBearerRequest struct {
	// Token is the raw bearer token supplied by the API client.
	Token string `json:"token"`
}

// AuthProvider requires all methods to be implemented.
// AuthProvider provides authentication via an external identity provider.
// This capability allows plugins to implement standards-based authentication
// flows (e.g. OpenID Connect / OAuth2) or proprietary identity protocols.
//
// The plugin is responsible for all protocol-level work: provider discovery,
// token exchange, credential/token verification and claim extraction. The
// host (Navidrome) is responsible for HTTP routing, CSRF state cookies,
// user provisioning and JWT session creation.
//
// Only one auth provider plugin can be active at a time. The plugin is
// considered active when its GetStatus returns Enabled=true.
//
// All methods are required.
type AuthProvider interface {
	// GetStatus - GetStatus returns the current status and public configuration of the auth provider.
	GetStatus(GetStatusRequest) (AuthStatus, error)
	// GetLoginURL - GetLoginURL generates the authorization URL used to start a login.
	GetLoginURL(GetLoginURLRequest) (GetLoginURLResponse, error)
	// ExchangeCode - ExchangeCode is called on the provider callback endpoint after the user authorizes the request.
	ExchangeCode(ExchangeCodeRequest) (AuthIdentity, error)
	// VerifyBearer - VerifyBearer validates a bearer token and returns the authenticated identity.
	VerifyBearer(VerifyBearerRequest) (AuthIdentity, error)
	// GetLogoutURL - GetLogoutURL returns the provider's single sign-out URL.
	GetLogoutURL(GetLogoutURLRequest) (GetLogoutURLResponse, error)
} // Internal implementation holders
var (
	getStatusImpl    func(GetStatusRequest) (AuthStatus, error)
	getLoginURLImpl  func(GetLoginURLRequest) (GetLoginURLResponse, error)
	exchangeCodeImpl func(ExchangeCodeRequest) (AuthIdentity, error)
	verifyBearerImpl func(VerifyBearerRequest) (AuthIdentity, error)
	getLogoutURLImpl func(GetLogoutURLRequest) (GetLogoutURLResponse, error)
)

// Register registers an auth provider implementation.
// All methods are required.
func Register(impl AuthProvider) {
	getStatusImpl = impl.GetStatus
	getLoginURLImpl = impl.GetLoginURL
	exchangeCodeImpl = impl.ExchangeCode
	verifyBearerImpl = impl.VerifyBearer
	getLogoutURLImpl = impl.GetLogoutURL
}

// NotImplementedCode is the standard return code for unimplemented functions.
// The host recognizes this and skips the plugin gracefully.
const NotImplementedCode int32 = -2

//go:wasmexport nd_auth_get_status
func _NdAuthGetStatus() int32 {
	if getStatusImpl == nil {
		// Return standard code - host will skip this plugin gracefully
		return NotImplementedCode
	}

	var input GetStatusRequest
	if err := pdk.InputJSON(&input); err != nil {
		pdk.SetError(err)
		return -1
	}

	output, err := getStatusImpl(input)
	if err != nil {
		pdk.SetError(err)
		return -1
	}

	if err := pdk.OutputJSON(output); err != nil {
		pdk.SetError(err)
		return -1
	}

	return 0
}

//go:wasmexport nd_auth_get_login_url
func _NdAuthGetLoginUrl() int32 {
	if getLoginURLImpl == nil {
		// Return standard code - host will skip this plugin gracefully
		return NotImplementedCode
	}

	var input GetLoginURLRequest
	if err := pdk.InputJSON(&input); err != nil {
		pdk.SetError(err)
		return -1
	}

	output, err := getLoginURLImpl(input)
	if err != nil {
		pdk.SetError(err)
		return -1
	}

	if err := pdk.OutputJSON(output); err != nil {
		pdk.SetError(err)
		return -1
	}

	return 0
}

//go:wasmexport nd_auth_exchange_code
func _NdAuthExchangeCode() int32 {
	if exchangeCodeImpl == nil {
		// Return standard code - host will skip this plugin gracefully
		return NotImplementedCode
	}

	var input ExchangeCodeRequest
	if err := pdk.InputJSON(&input); err != nil {
		pdk.SetError(err)
		return -1
	}

	output, err := exchangeCodeImpl(input)
	if err != nil {
		pdk.SetError(err)
		return -1
	}

	if err := pdk.OutputJSON(output); err != nil {
		pdk.SetError(err)
		return -1
	}

	return 0
}

//go:wasmexport nd_auth_verify_bearer
func _NdAuthVerifyBearer() int32 {
	if verifyBearerImpl == nil {
		// Return standard code - host will skip this plugin gracefully
		return NotImplementedCode
	}

	var input VerifyBearerRequest
	if err := pdk.InputJSON(&input); err != nil {
		pdk.SetError(err)
		return -1
	}

	output, err := verifyBearerImpl(input)
	if err != nil {
		pdk.SetError(err)
		return -1
	}

	if err := pdk.OutputJSON(output); err != nil {
		pdk.SetError(err)
		return -1
	}

	return 0
}

//go:wasmexport nd_auth_get_logout_url
func _NdAuthGetLogoutUrl() int32 {
	if getLogoutURLImpl == nil {
		// Return standard code - host will skip this plugin gracefully
		return NotImplementedCode
	}

	var input GetLogoutURLRequest
	if err := pdk.InputJSON(&input); err != nil {
		pdk.SetError(err)
		return -1
	}

	output, err := getLogoutURLImpl(input)
	if err != nil {
		pdk.SetError(err)
		return -1
	}

	if err := pdk.OutputJSON(output); err != nil {
		pdk.SetError(err)
		return -1
	}

	return 0
}