package capabilities

// AuthProvider provides authentication via an external identity provider.
// This capability allows plugins to implement standards-based authentication
// flows (e.g. OpenID Connect / OAuth2) or proprietary identity protocols.
//
// The plugin is responsible for all protocol-level work: provider discovery,
// token exchange, credential/token verification and claim extraction. The
// host (Navidrome) is responsible for HTTP routing, CSRF state cookies,
// user provisioning and JWT session creation.
//
// Only one auth provider plugin can be active at a time. The plugin is
// considered active when its GetStatus returns Enabled=true.
//
// All methods are required.
//
//nd:capability name=auth_provider required=true
type AuthProvider interface {
	// GetStatus returns the current status and public configuration of the
	// auth provider. The host calls this to decide whether a provider is
	// enabled and to render the login page SSO button.
	//nd:export name=nd_auth_get_status
	GetStatus(GetStatusRequest) (AuthStatus, error)

	// GetLoginURL generates the authorization URL used to start a login.
	// The host generates the state and nonce values (stored in HttpOnly
	// cookies for CSRF protection) and passes them along with the callback
	// redirect URI. The plugin MUST echo these values in the returned URL.
	//nd:export name=nd_auth_get_login_url
	GetLoginURL(GetLoginURLRequest) (GetLoginURLResponse, error)

	// ExchangeCode is called on the provider callback endpoint after the
	// user authorizes the request. It trades the authorization code for
	// tokens, validates them, and returns the authenticated identity.
	//
	// The ID token returned in AuthIdentity is stored by the host so it can
	// be passed back later as an id_token_hint during logout.
	//nd:export name=nd_auth_exchange_code
	ExchangeCode(ExchangeCodeRequest) (AuthIdentity, error)

	// VerifyBearer validates a bearer token (e.g. an OIDC ID token) passed
	// by an API client and returns the authenticated identity. This is used
	// by the Subsonic API and the native API to authenticate non-browser
	// clients using the external provider's tokens.
	//nd:export name=nd_auth_verify_bearer
	VerifyBearer(VerifyBearerRequest) (AuthIdentity, error)

	// GetLogoutURL returns the provider's single sign-out URL. The host
	// redirects the browser there after a Navidrome session logout. If the
	// provider does not support single sign-out, return an empty LogoutURL.
	//nd:export name=nd_auth_get_logout_url
	GetLogoutURL(GetLogoutURLRequest) (GetLogoutURLResponse, error)
}

// GetStatusRequest wraps the context the host can provide for a status query.
type GetStatusRequest struct {
	// AppURL is the base URL of the Navidrome web app (e.g. https://nd.local/app).
	// Used by the plugin to build absolute redirect/logout URLs.
	AppURL string `json:"appUrl"`
}

// AuthStatus describes the provider's current state for the login page and host.
type AuthStatus struct {
	// Enabled indicates the provider is fully configured and can handle logins.
	Enabled bool `json:"enabled"`
	// ButtonText is the label for the SSO button on the login page.
	ButtonText string `json:"buttonText,omitempty"`
	// AutoRedirect indicates the login page should skip the local form and
	// redirect straight to the provider.
	AutoRedirect bool `json:"autoRedirect,omitempty"`
	// ProviderID is a stable identifier of the provider (e.g. "oidc").
	ProviderID string `json:"providerId,omitempty"`
	// Issuer is the identity provider identifier, when applicable.
	Issuer string `json:"issuer,omitempty"`
	// ClientID is the public OAuth2 client identifier, when applicable.
	ClientID string `json:"clientId,omitempty"`
	// Scopes are the OAuth2 scopes requested from the provider, when applicable.
	Scopes []string `json:"scopes,omitempty"`
	// LogoutURL is the provider logout URL used by the admin settings page.
	LogoutURL string `json:"logoutUrl,omitempty"`
	// MatchBy describes how usernames are derived, when applicable.
	MatchBy string `json:"matchBy,omitempty"`
}

// GetLoginURLRequest carries the values required to build an authorization URL.
type GetLoginURLRequest struct {
	// State is the CSRF state token generated by the host. Must be included
	// verbatim in the authorization URL.
	State string `json:"state"`
	// Nonce is the request nonce generated by the host. Must be included
	// verbatim in the authorization URL.
	Nonce string `json:"nonce"`
	// RedirectURI is the callback URI the provider must redirect to after
	// user consent.
	RedirectURI string `json:"redirectUri"`
}

// GetLoginURLResponse is the result of GetLoginURL.
type GetLoginURLResponse struct {
	// AuthorizationURL is the full URL the browser should be redirected to.
	AuthorizationURL string `json:"authorizationUrl"`
}

// ExchangeCodeRequest carries the callback parameters for the code exchange.
type ExchangeCodeRequest struct {
	// Code is the authorization code received on the callback.
	Code string `json:"code"`
	// State is the state echoed back by the provider on the callback.
	State string `json:"state"`
	// Nonce is the nonce value the host stored in the login cookie.
	Nonce string `json:"nonce"`
	// RedirectURI is the same redirect URI that was used to build the
	// authorization URL.
	RedirectURI string `json:"redirectUri"`
}

// AuthIdentity represents an authenticated user resolved from the provider.
type AuthIdentity struct {
	// Provider is the identity provider name (e.g. "oidc").
	Provider string `json:"provider"`
	// Subject is the provider's immutable subject identifier for the user.
	Subject string `json:"subject"`
	// Username is the username to provision/authenticate in Navidrome.
	Username string `json:"username"`
	// Email is the user's email address, if available.
	Email string `json:"email,omitempty"`
	// DisplayName is the user's display name, if available.
	DisplayName string `json:"displayName,omitempty"`
	// Groups are the user's group memberships, if available.
	Groups []string `json:"groups,omitempty"`
	// IsAdmin indicates the user should be granted admin rights. When true,
	// the host promotes the user to admin on login.
	IsAdmin bool `json:"isAdmin,omitempty"`
	// IDToken is the raw ID token (or equivalent) returned by the provider.
	// Used as an id_token_hint during single sign-out.
	IDToken string `json:"idToken,omitempty"`
	// Claims contains the raw identity claims for display or debugging.
	Claims map[string]any `json:"claims,omitempty"`
}

// VerifyBearerRequest carries a bearer token to validate.
type VerifyBearerRequest struct {
	// Token is the raw bearer token supplied by the API client.
	Token string `json:"token"`
}

// GetLogoutURLRequest carries the parameters for building a single sign-out URL.
type GetLogoutURLRequest struct {
	// PostLogoutRedirectURI is where the provider should send the browser
	// after the local session has been torn down.
	PostLogoutRedirectURI string `json:"postLogoutRedirectUri,omitempty"`
	// IDTokenHint is the user's ID token, used as the id_token_hint parameter.
	IDTokenHint string `json:"idTokenHint,omitempty"`
}

// GetLogoutURLResponse is the result of GetLogoutURL.
type GetLogoutURLResponse struct {
	// LogoutURL is the provider's single sign-out URL. Empty when the
	// provider does not support it.
	LogoutURL string `json:"logoutUrl,omitempty"`
}